//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18046
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filewatcher.GUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SAVEHISTORIES {
            get {
                return ((bool)(this["SAVEHISTORIES"]));
            }
            set {
                this["SAVEHISTORIES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SAVEOUTPUT {
            get {
                return ((bool)(this["SAVEOUTPUT"]));
            }
            set {
                this["SAVEOUTPUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SHOWPOPUPS {
            get {
                return ((bool)(this["SHOWPOPUPS"]));
            }
            set {
                this["SHOWPOPUPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SAVEOUTPUTLOCATION {
            get {
                return ((string)(this["SAVEOUTPUTLOCATION"]));
            }
            set {
                this["SAVEOUTPUTLOCATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WATCHVIEW_LEFT {
            get {
                return ((double)(this["WATCHVIEW_LEFT"]));
            }
            set {
                this["WATCHVIEW_LEFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WATCHVIEW_TOP {
            get {
                return ((double)(this["WATCHVIEW_TOP"]));
            }
            set {
                this["WATCHVIEW_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MACROVIEW_LEFT {
            get {
                return ((double)(this["MACROVIEW_LEFT"]));
            }
            set {
                this["MACROVIEW_LEFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MACROVIEW_TOP {
            get {
                return ((double)(this["MACROVIEW_TOP"]));
            }
            set {
                this["MACROVIEW_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MAINVIEW_LEFT {
            get {
                return ((double)(this["MAINVIEW_LEFT"]));
            }
            set {
                this["MAINVIEW_LEFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MAINVIEW_TOP {
            get {
                return ((double)(this["MAINVIEW_TOP"]));
            }
            set {
                this["MAINVIEW_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MAINVIEW_WIDTH {
            get {
                return ((double)(this["MAINVIEW_WIDTH"]));
            }
            set {
                this["MAINVIEW_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MAINVIEW_HEIGHT {
            get {
                return ((double)(this["MAINVIEW_HEIGHT"]));
            }
            set {
                this["MAINVIEW_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SHOWMESSAGE_SHELLEXECUTE {
            get {
                return ((bool)(this["SHOWMESSAGE_SHELLEXECUTE"]));
            }
            set {
                this["SHOWMESSAGE_SHELLEXECUTE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SHOWMESSAGE_OUTPUTPATH {
            get {
                return ((bool)(this["SHOWMESSAGE_OUTPUTPATH"]));
            }
            set {
                this["SHOWMESSAGE_OUTPUTPATH"] = value;
            }
        }
    }
}
